site_name: Pokemon Astral Warp
site_url: https://.github.io/pokemon-astral-warp
site_description: Wikipedia Page for the fan-game Pokemon Astral Warp
site_author: justPauw
repo_url: https://github.com//pokemon-astral-warp
theme:
  name: material
  features:
  - content.tabls.links
  - content.tooltips
  favicon: img/items/premier-ball.png
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: slate
    toggle:
      icon: material/eye
      name: Switch to light mode
nav:
- Home: index.md
- Item Changes: item_changes.md
- Pokemon: []
- Routes: []
plugins:
- search:
    lang: en
markdown_extensions:
- admonition
- abbr
- attr_list
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
extra_css:
- stylesheets/extra.css
